#!/usr/bin/env python3
import argparse,json,subprocess,time,zipfile
from pathlib import Path
SURFACE="ADMINISTRATUM_FINAL_REPORT_BUNDLE_BUILDER_V0_1"
def git(repo,*args):
    p=subprocess.run(["git","-C",str(repo),*args],text=True,capture_output=True); return p.stdout + p.stderr
def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--repo-root',default='.'); ap.add_argument('cmd',nargs='?',default='build'); args=ap.parse_args(); repo=Path(args.repo_root).resolve()
    out=repo/'ORGANS'/'IMPERIAL_IDE'/'STATION'/'reports'/'FINAL_REPORT_BUNDLES'; out.mkdir(parents=True,exist_ok=True); stamp=time.strftime('%Y%m%d_%H%M%S')
    work=out/f'final_report_bundle_{stamp}'; work.mkdir(parents=True,exist_ok=True)
    (work/'GIT_STATUS.txt').write_text(git(repo,'status','--short'),encoding='utf-8')
    (work/'GIT_DIFF_STAT.txt').write_text(git(repo,'diff','--stat'),encoding='utf-8')
    (work/'OWNER_SUMMARY_RU.md').write_text('# Owner summary\n\nFinal bundle generated by Administratum. Review before commit/push.\n',encoding='utf-8')
    ws=repo/'ORGANS'/'IMPERIAL_IDE'/'WEB_SANCTUM'/'test-results'/'screenshots'
    if ws.exists():
        dest=work/'screenshots'; dest.mkdir(exist_ok=True)
        for p in ws.glob('*.png'):
            (dest/p.name).write_bytes(p.read_bytes())
    zip_path=out/f'FINAL_REPORT_BUNDLE_{stamp}.zip'
    with zipfile.ZipFile(zip_path,'w',zipfile.ZIP_DEFLATED) as z:
        for p in work.rglob('*'):
            if p.is_file(): z.write(p,p.relative_to(work))
    print(json.dumps({'status':'PASS','surface':SURFACE,'bundle':str(zip_path)},indent=2))
if __name__=='__main__': main()
