
import { invoke } from '@tauri-apps/api/core';
const FPS_LOCK_TARGET=60, FPS_SOFT_WARNING=55, FPS_HARD_FAIL=50, FRAME_BUDGET_MS=16.67;
let fpsSamples=[],lastFrame=performance.now(),reduceMotionMode=false,state={},active='ASTRONOMICON';
const organs=[{id:'ASTRONOMICON',sub:'CROWN-CONFIRMED 1/10',actions:['status','astronomicon-advice','astronomicon-redblue','astronomicon-hardening','score-refresh-guidance']},{id:'CUSTODES',sub:'Прокурорская проверка',actions:['custodes-audit','custodes-readout']},{id:'THRONE',sub:'Crown order / anti-self-deception',actions:['throne-crown-order','throne-readout']},{id:'PACK_FORGE',sub:'Patch Pack / Task Pack request drafts',actions:['register-patch-pack','register-task-pack']},{id:'EYES_ROOM',sub:'Eyes 0.5.3.1 contract',actions:['eyes-contract','eyes-notes','eyes-context-level','eyes-screenshot-sweep']},{id:'SEED_CORE',sub:'Seed Core draft contract',actions:['seed-contract','seed-status']}];
const labels={'status':'Статус Империума','astronomicon-advice':'Астрономикон: совет','astronomicon-redblue':'Астрономикон: Red/Blue','astronomicon-hardening':'Астрономикон: hardening','score-refresh-guidance':'Подсказка обновления цифр','custodes-audit':'Кустодес: audit','custodes-readout':'Кустодес: docket','throne-crown-order':'Трон: Crown order','throne-readout':'Трон: verdict','register-patch-pack':'Регистрация Patch Pack','register-task-pack':'Регистрация Task Pack','eyes-contract':'Eyes contract','eyes-notes':'Eyes notes','eyes-context-level':'Eyes context level','eyes-screenshot-sweep':'Eyes screenshot sweep','seed-contract':'Seed contract','seed-status':'Seed status'};
function log(m,l='info'){const b=document.querySelector('#log');const d=document.createElement('div');d.className='log-line '+l;d.textContent=`[${new Date().toLocaleTimeString('ru-RU')}][${l.toUpperCase()}] ${m}`;b.appendChild(d);b.scrollTop=b.scrollHeight}
function startFpsWatchdog(){const chip=document.querySelector('#fps');function tick(now){const delta=now-lastFrame;lastFrame=now;const fps=1000/Math.max(delta,1);fpsSamples.push(fps);if(fpsSamples.length>180)fpsSamples.shift();const avg=fpsSamples.reduce((a,b)=>a+b,0)/fpsSamples.length;chip.textContent=`FPS ${avg.toFixed(1)} / target ${FPS_LOCK_TARGET}`;chip.classList.toggle('warn',avg<FPS_SOFT_WARNING&&avg>=FPS_HARD_FAIL);chip.classList.toggle('fail',avg<FPS_HARD_FAIL);if(avg<FPS_SOFT_WARNING&&fpsSamples.length>=120){reduceMotionMode=true;document.body.classList.add('reduce-motion')}requestAnimationFrame(tick)}requestAnimationFrame(tick);if('PerformanceObserver'in window){try{new PerformanceObserver(list=>{for(const e of list.getEntries()){if(e.duration>FRAME_BUDGET_MS*3)log(`Long task ${e.duration.toFixed(1)}ms`,'error')}}).observe({entryTypes:['longtask']})}catch{}}}
function render(){document.querySelector('#app').innerHTML=`<main class='shell'><header class='header'><div class='brand'>IMPERIUM</div><div><div id='level'>LEVEL -- | Proof XP -- | Стрик --</div><div class='xp-track'><div class='xp-fill' id='xp'></div></div></div><div class='fps-chip' id='fps'>FPS --</div></header><section class='main'><aside class='panel'><div class='title'>ORGAN_HUB</div><div id='organ-list' class='organ-list'></div></aside><section class='panel room'><div class='room-head'><div><div class='room-title' id='room-title'></div><div id='room-sub'></div></div><div class='energy'></div></div><div class='room-actions' id='actions'></div><div class='room-body'><div id='telemetry'></div><div id='room-panel'></div></div></section><aside class='panel aquarium' data-stream='AQUARIUM_STREAM'><div class='title'>AQUARIUM</div><div class='log-box' id='log'></div><div class='controls'><button class='action-btn' id='copy'>Копировать</button><button class='action-btn' id='clear'>Очистить</button><button class='action-btn' id='refresh'>Обновить</button></div></aside></section></main>`;document.querySelector('#copy').onclick=()=>navigator.clipboard.writeText(document.querySelector('#log').innerText).then(()=>log('Aquarium copied','pass'));document.querySelector('#clear').onclick=()=>document.querySelector('#log').innerHTML='';document.querySelector('#refresh').onclick=refreshImperiumState;renderOrgans();openOrgan('ASTRONOMICON')}
function renderOrgans(){const list=document.querySelector('#organ-list');list.innerHTML='';for(const o of organs){const c=document.createElement('div');c.className='organ-card';c.dataset.organ=o.id;c.innerHTML=`<div class='organ-id'>${o.id}</div><div class='organ-state'>${o.sub}</div>`;c.onclick=()=>openOrgan(o.id);list.appendChild(c)}}
function openOrgan(id){active=id;const o=organs.find(x=>x.id===id);document.querySelectorAll('.organ-card').forEach(x=>x.classList.toggle('active',x.dataset.organ===id));document.querySelector('#room-title').textContent=o.id;document.querySelector('#room-sub').textContent=o.sub;document.querySelector('#actions').innerHTML='';for(const a of o.actions){const b=document.createElement('button');b.className='action-btn';b.textContent=labels[a]||a;b.onclick=()=>routeAction(a);document.querySelector('#actions').appendChild(b)}renderTelemetry();renderRoomPanel();log(`Entered room ${id}`,'auth')}
function metric(k,v){return `<div class='metric-card'><div class='metric-label'>${k}</div><div class='metric-value'>${v??'—'}</div></div>`}
function renderTelemetry(){const c=state?.crown_aware_scores||{};document.querySelector('#telemetry').innerHTML=metric('CROWN_AWARE_OVERLAY',state?.stage_integration_mode)+metric('Red',c.red_team_score)+metric('Blue',c.blue_team_score)+metric('Custodes',c.custodes_organ_validators_score)+metric('Throne',c.throne_organ_validators_score)+metric('Assembled',c.organ_assembled_score)}
function renderRoomPanel(){let html='';if(active==='EYES_ROOM')html=metric('EYES_ROOM','v0.5.3.1 contract')+metric('Notes','planned')+metric('Context levels','planned')+metric('Screenshot sweep','planned');else if(active==='SEED_CORE')html=metric('SEED_CORE','draft')+metric('IDE binding','future')+metric('Patch inheritance','future');else if(active==='PACK_FORGE')html=metric('Patch Pack request','available')+metric('Task Pack request','available')+metric('Canonical registrar','future');else html=metric('Organ',active)+metric('Aquarium','visible');document.querySelector('#room-panel').innerHTML=html}
async function refreshImperiumState(){try{state=await invoke('read_imperium_state');renderTelemetry();renderRoomPanel();const xp=state?.proof_xp||0;document.querySelector('#level').textContent=`LEVEL ${Math.floor(xp/100)+1} | Proof XP ${xp} | Стрик ${state?.clean_streak??0}`;document.querySelector('#xp').style.width=`${xp%100}%`;log('Imperium state refreshed','pass')}catch(e){log(`refresh failed: ${e}`,'error')}}
async function routeAction(a){if(a==='register-patch-pack')return createPackRequest('PATCH_PACK');if(a==='register-task-pack')return createPackRequest('TASK_PACK');if(a.startsWith('eyes-'))return openEyesRoom(a);if(a.startsWith('seed-'))return openSeedCore(a);return runImperiumAction(a)}
async function runImperiumAction(actionId){log(`RUN_ACTION ${actionId}`,'auth');try{const r=await invoke('run_imperium_action',{actionId});log(r.stdout||'(no stdout)',r.exit_code===0?'pass':'error');if(r.stderr)log(r.stderr,'error');log(`ACTION_EXIT_CODE ${r.exit_code}`,r.exit_code===0?'pass':'error');await refreshImperiumState()}catch(e){log(`ACTION_FAILED ${e}`,'error')}}
async function createPackRequest(kind){const packId=prompt(`${kind}: Pack ID`);if(!packId)return;const title=prompt(`${kind}: title`,packId)||packId;try{const r=await invoke('create_pack_request',{kind,packId,title,targetOrgan:'ASTRONOMICON'});log(`PACK_REQUEST_CREATED ${r.request}`,'pass');log(`PACK_REQUEST_RECEIPT ${r.receipt}`,'pass')}catch(e){log(`PACK_REQUEST_FAILED ${e}`,'error')}}
async function openEyesRoom(a){log(`EYES_ROOM ${a}`,'auth');try{log(JSON.stringify(await invoke('read_eyes_contract'),null,2),'auth')}catch(e){log(`EYES_FAILED ${e}`,'error')}}
async function openSeedCore(a){log(`SEED_CORE ${a}`,'auth');try{log(JSON.stringify(await invoke('read_seed_core_contract'),null,2),'auth')}catch(e){log(`SEED_FAILED ${e}`,'error')}}
render();startFpsWatchdog();refreshImperiumState();
