
use chrono::Utc;use serde::{Deserialize,Serialize};use serde_json::{json,Value};use std::{fs,path::{Path,PathBuf},process::Command};
#[derive(Debug,Serialize,Deserialize)]struct ActionResult{action_id:String,exit_code:i32,stdout:String,stderr:String,app_log:String,receipt:String}
#[derive(Debug,Serialize,Deserialize)]struct PackRequestResult{request:String,receipt:String}
fn repo_root()->Result<PathBuf,String>{let cwd=std::env::current_dir().map_err(|e|e.to_string())?;for c in [cwd.clone(),cwd.join("../.."),cwd.join("../../..")]{let p=c.canonicalize().unwrap_or(c);if p.join("ORGANS").exists()&&p.join("WARP").exists(){return Ok(p)}}Err("repo root not found".into())}
fn read_json(p:&Path)->Value{serde_json::from_str(&fs::read_to_string(p).unwrap_or_else(|_|"{}".into())).unwrap_or_else(|_|json!({}))}
fn rel(p:&Path,r:&Path)->String{p.strip_prefix(r).unwrap_or(p).to_string_lossy().replace("\\","/")}
fn write_json(p:&Path,v:&Value)->Result<(),String>{if let Some(d)=p.parent(){fs::create_dir_all(d).map_err(|e|e.to_string())?}fs::write(p,serde_json::to_string_pretty(v).map_err(|e|e.to_string())?+"\n").map_err(|e|e.to_string())}
fn clean_streak(_root:&Path)->i64{0}
fn proof_xp(s:&Value)->i64{let mut xp=0;if s.get("astronomicon_chain_ok").and_then(|v|v.as_bool())==Some(true){xp+=100}if s.get("stage_integrates_local_crown").and_then(|v|v.as_bool())==Some(true){xp+=100}if let Some(c)=s.get("crown_aware_scores").and_then(|v|v.as_object()){for k in ["red_team_score","blue_team_score","custodes_organ_validators_score","throne_organ_validators_score","trust_proven_score","rule_validated_score","tui_launcher_presence_score","throne_confirmed_score"]{xp+=c.get(k).and_then(|v|v.as_f64()).unwrap_or(0.0)as i64}}xp}
#[tauri::command]fn read_imperium_state()->Result<Value,String>{let root=repo_root()?;let mut s=read_json(&root.join("ORGANS/THRONE/REPORTS/POST_ASTRONOMICON_SCORE_READOUT_SUMMARY_V0_1.json"));let streak=clean_streak(&root);s["proof_xp"]=json!(proof_xp(&s)+(streak*5).min(100));s["clean_streak"]=json!(streak);s["tauri_shell"]=json!("IMPERIUM_TAURI_SHELL_FOUNDATION");Ok(s)}
#[tauri::command]fn run_imperium_action(action_id:String)->Result<ActionResult,String>{let allowed=["status","astronomicon-advice","astronomicon-redblue","astronomicon-hardening","custodes-audit","throne-crown-order","throne-readout","custodes-readout","score-refresh-guidance"];if !allowed.contains(&action_id.as_str()){return Err(format!("action not allowed: {action_id}"))}let root=repo_root()?;let tui=root.join("SUPPORT/TUI/imperium_tui.py");let out=Command::new("python").current_dir(&root).arg(&tui).arg("--repo-root").arg(&root).arg("--action").arg(&action_id).output().map_err(|e|e.to_string())?;let code=out.status.code().unwrap_or(-1);let stdout=String::from_utf8_lossy(&out.stdout).to_string();let stderr=String::from_utf8_lossy(&out.stderr).to_string();let stamp=Utc::now().format("%Y%m%d_%H%M%S").to_string();let log=root.join("SUPPORT/APP_TAURI/logs").join(format!("{stamp}_{action_id}.log"));let rec=root.join("SUPPORT/APP_TAURI/receipts").join(format!("{stamp}_{action_id}_receipt.json"));if let Some(d)=log.parent(){fs::create_dir_all(d).map_err(|e|e.to_string())?}fs::write(&log,format!("ACTION: {action_id}\nEXIT: {code}\n\nSTDOUT:\n{stdout}\nSTDERR:\n{stderr}\n")).map_err(|e|e.to_string())?;write_json(&rec,&json!({"verdict":if code==0{"PASS_TAURI_ACTION_AQUARIUM_RUN"}else{"FAIL_TAURI_ACTION_AQUARIUM_RUN"},"action_id":action_id,"exit_code":code,"app_log":rel(&log,&root),"generated_at_utc":Utc::now().to_rfc3339(),"errors":if code==0{json!([])}else{json!(["non-zero exit"])}}))?;Ok(ActionResult{action_id,exit_code:code,stdout,stderr,app_log:rel(&log,&root),receipt:rel(&rec,&root)})}
#[tauri::command]fn create_pack_request(kind:String,pack_id:String,title:String,target_organ:String)->Result<PackRequestResult,String>{let root=repo_root()?;let stamp=Utc::now().format("%Y%m%d_%H%M%S").to_string();let req=root.join("SUPPORT/APP_TAURI/receipts").join(format!("{stamp}_{kind}_{pack_id}_request.json"));let rec=root.join("SUPPORT/APP_TAURI/receipts").join(format!("{stamp}_{kind}_{pack_id}_receipt.json"));write_json(&req,&json!({"kind":kind,"pack_id":pack_id,"title":title,"target_organ":target_organ,"status":"TAURI_APP_REQUEST_DRAFT_NOT_CANONICAL_REGISTRATION"}))?;write_json(&rec,&json!({"verdict":"PASS_TAURI_PACK_REQUEST_DRAFTED","request":rel(&req,&root),"warnings":["not canonical registration"]}))?;Ok(PackRequestResult{request:rel(&req,&root),receipt:rel(&rec,&root)})}
#[tauri::command]fn read_eyes_contract()->Result<Value,String>{let root=repo_root()?;Ok(read_json(&root.join("SUPPORT/APP_TAURI/contracts/IMPERIUM_EYES_ROOM_CONTRACT_V0_1.json")))}
#[tauri::command]fn read_seed_core_contract()->Result<Value,String>{let root=repo_root()?;Ok(read_json(&root.join("SUPPORT/APP_TAURI/contracts/IMPERIUM_SEED_CORE_CONTRACT_DRAFT_V0_1.json")))}
#[tauri::command]fn app_selftest()->Result<Value,String>{Ok(json!({"verdict":"PASS_IMPERIUM_TAURI_APP_SELFTEST","not_claimed":["packaged exe","Eyes embedded","auto-updater"]}))}
fn main(){tauri::Builder::default().plugin(tauri_plugin_opener::init()).invoke_handler(tauri::generate_handler![read_imperium_state,run_imperium_action,create_pack_request,read_eyes_contract,read_seed_core_contract,app_selftest]).run(tauri::generate_context!()).expect("error while running Imperium Tauri app");}
